apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: mcp-server-everything-rlp
  namespace: mcp-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mcp-server-everything
  defaults:
    limits:
      "low-limit":
        rates:
        - limit: 5
          window: 10s
