apiVersion: v1
kind: Namespace
metadata:
  name: mcp-server  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-everything
  namespace: mcp-server
  labels:
    app: mcp-server-everything
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-everything
  template:
    metadata:
      labels:
        app: mcp-server-everything
    spec:
      containers:
        - name: mcp-server-everything
          image: quay.io/${QUAY_USERNAME}/mcp-server-everything:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-everything
  namespace: mcp-server
spec:
  selector:
    app: mcp-server-everything
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3001
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-server-everything
  namespace: mcp-server
spec:
  parentRefs:
    - name: mcp-server-everything
      namespace: mcp-gateway
  hostnames:
    - api.${KUADRANT_ZONE_ROOT_DOMAIN}
  rules:
    - matches:
        - method: POST
          path:
            type: PathPrefix
            value: /mcp
        - method: GET
          path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: mcp-server-everything
          port: 443